name: Build main and frontend
on:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - run: rustup toolchain install --profile minimal
      - uses: Swatinem/rust-cache@v2

      # builds main.rs
      - name: Build project
        run: cargo build --release --target=${{ matrix.target }}

      # builds frontend with wasm-pack
      - uses: bahmutov/npm-install@v1
      - run: yarn run wasm-pack build frontend
      - run: yarn run build
